### ISSUE TITLE
T130 should be R130

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-website#1]
There seems to be a number of R examples that are showing as T on the website, but not on the Google spreadsheet master. The correct label is given on the work page but not the home page.
https://polyrhythm.humdrum.org/example/?id=130

Here is a partial list of other mislabeled examples on the home page:
161
180
183
187
299
308B
310
324
350

**Comment by craigsapp** [comment]
Fixed.  The problem was that I was using the wrong column in the master spreadsheet.  I was using the "Work Dataset" column rather than the "Example Dataset" column.  The work dataset has three states: "R",  "T", and "B" (B meaning the work has both reserve and test data examples).  The Example dataset column only has "R" and "T" entries.  I was marking works that had "R" label as "R", and the rest (T and B) as T.

Now for example 130 is in bold (meaning reserve dataset):

<img width="1184" alt="Screen Shot 2019-10-12 at 11 46 46 AM" src="https://user-images.githubusercontent.com/3487289/66706305-cc412c80-ece5-11e9-8dcc-113b8f53e5bf.png">
