### ISSUE TITLE
VHV button on Polyrhythm Website sends to wrong example when scrolling from example to example

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-website#10]
For example, when clocking VHV button for R130, VHV opens with R129. This doesn't happen if the example isn access thought the Home page.

**Comment by craigsapp** [comment]
This is probably fixed.  The general problem is that the URL viewed at the top of the page is no longer valid when using the arrow buttons to navigate to another example.  The problem is that the id number in the URL cannot be changed when using the method of navigating between examples on the page.  If the URL were to be updated, the page would reload.  This in turn would cause verovio to be reloaded, taking several seconds more to display the notation than the current method.

I added a "link" button above each example (in the yellow button section):

<img width="1287" alt="Screen Shot 2019-12-31 at 23 03 07" src="https://user-images.githubusercontent.com/3487289/71638950-22a57380-2c22-11ea-8e86-62dc123a166d.png">

Notice that the URL on the page is:

https://polyrhythm.humdrum.org/example/?id=129

for example 129, but the right navigation button was pressed several times to get to example 144.  

If you click on the "link" button, this text will be copied to the system clipboard, and which you can paste into an email or a new webpage to view the current example (144) rather than the original example when loading the example page (129):

https://polyrhythm.humdrum.org/example/?id=144

==========

Also, the "VHV" link has been disabled (at least for now as discussed).  There is instead a "copy" button which copies the data for the example, which can then in turn be pasted into the VHV editor:

<img width="1287" alt="Screen Shot 2019-12-31 at 23 09 42" src="https://user-images.githubusercontent.com/3487289/71638971-a3646f80-2c22-11ea-91d4-1aeb87580384.png">
