### ISSUE TITLE
Slur Positioning

### ISSUE THREAD

**Issue by Boardbreak** [polyrhythm-project/polyrhythm-website#15]
In Ex. T433, by Berg, the slurs on the first beat of the 1st and 2nd measures in the Bass clef are colliding with the beams.

**Comment by craigsapp** [comment]
I do not see that:

https://polyrhythm.humdrum.org/example/?id=433

<img width="631" alt="Screen Shot 2020-01-18 at 22 56 50" src="https://user-images.githubusercontent.com/3487289/72676416-de99d780-3a45-11ea-8e69-754c1aca5d95.png">


Do you see the same thing?  If not, then post a screenshot of what you see.

In any case, this will not be fixable in the near and probably medium future for several reasons: (1) The MusicXML data will not have the necessary information in order to specify an explicit layout for the slur, and (2) automatic slur placement is difficult, so verovio will not always get it correct (but I can report it to the verovio repository if it is very bad).
