### ISSUE TITLE
Slur issues

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#23]
ex. T323, Bartok, 1st violin, bar 2, SIB . pdf has a slur and it is missing from VHV

**Comment by cdf75ubc** [comment]
ex. T328, Bartok, bar 4, on VHV the slur should end on 1st beat and it is prolongated to next tone.

**Comment by craigsapp** [comment]
T323 desired:

<img width="853" alt="Screen Shot 2020-01-18 at 19 02 38" src="https://user-images.githubusercontent.com/3487289/72673898-278d6400-3a25-11ea-824f-723299d35cdc.png">

Actual:

https://polyrhythm.humdrum.org/example/?id=323

<img width="801" alt="Screen Shot 2020-01-18 at 19 03 22" src="https://user-images.githubusercontent.com/3487289/72673901-3bd16100-3a25-11ea-86bb-68b769762e79.png">

----------------

T328 desired rendering:

<img width="190" alt="Screen Shot 2020-01-18 at 19 10 09" src="https://user-images.githubusercontent.com/3487289/72673971-26106b80-3a26-11ea-868d-ac48d5014ad5.png">

Actual rendering:

<img width="261" alt="Screen Shot 2020-01-18 at 19 10 32" src="https://user-images.githubusercontent.com/3487289/72673977-36284b00-3a26-11ea-901d-e26766b0461c.png">

This is an error in the Sibelius file.  The slur looks correct in the PDF from Sibelius, but the MusicXML export is incorrect:

```xml
                        <note>
                                <pitch>
                                        <step>A</step>
                                        <octave>4</octave>
                                </pitch>
                                <duration>384</duration>
                                <voice>1</voice>
                                <type>eighth</type>
                                <stem>down</stem>
                                <staff>1</staff>
                                <beam number='1'>begin</beam>
                                <notations>
                                        <slur type='stop' number='1'/>
                                        <articulations>
                                                <staccato/>
                                        </articulations>
                                </notations>
                        </note>
                        <note>
                                <chord/>
                                <pitch>
                                        <step>E</step>
                                        <octave>5</octave>
                                </pitch>
                                <duration>384</duration>
                                <voice>1</voice>
                                <type>eighth</type>
                                <stem>down</stem>
                                <staff>1</staff>
                        </note>
                        <note>
                                <pitch>
                                        <step>A</step>
                                        <octave>4</octave>
                                </pitch>
                                <duration>192</duration>
                                <voice>1</voice>
                                <type>16th</type>
                                <stem>down</stem>
                                <staff>1</staff>
                                <beam number='1'>continue</beam>
                                <beam number='2'>begin</beam>
                                <notations>
                                        <slur type='start' number='1'/>
                                        <slur type='stop' number='2'/>
                                </notations>
                        </note>
```

I fixed the problem in the Humdrum file, but probably best to fix also in the Sibelius and MusicXML files (otherwise, it is likely that the problem will occur again if the Humdrum data is converted again from MusicXML file).

Here is the fixed version online:

<img width="1502" alt="Screen Shot 2020-01-18 at 19 24 41" src="https://user-images.githubusercontent.com/3487289/72674144-4ccfa180-3a28-11ea-8359-93e4e8055129.png">

**Comment by craigsapp** [comment]
T238 problem is fixed (but should be fixed in Sibelius and MusicXML files as well).

T323 problem is the same as in issue https://github.com/polyrhythm-project/polyrhythm-website/issues/13, so this particular issue will be closed.
