### ISSUE TITLE
Arpeggio lines

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#34]
ex. T329, Bartok, bar 11, broken chord symbol is missing from VHV.

**Comment by craigsapp** [comment]
Desired:

<img width="396" alt="Screen Shot 2020-01-18 at 22 01 40" src="https://user-images.githubusercontent.com/3487289/72675778-274d9280-3a3e-11ea-93c9-dcd190eed3bf.png">

(although there is a bug in how Sibelius is rendering it).

And the actual rendering with no arpeggio line:

https://polyrhythm.humdrum.org/example/?id=329

<img width="247" alt="Screen Shot 2020-01-18 at 22 01 44" src="https://user-images.githubusercontent.com/3487289/72675784-38969f00-3a3e-11ea-974d-d24544984ce8.png">

**Comment by craigsapp** [comment]
I fixed the Humdrum file:

<img width="210" alt="Screen Shot 2020-01-18 at 22 07 04" src="https://user-images.githubusercontent.com/3487289/72675830-f588fb80-3a3e-11ea-9596-26b8db460f52.png">


But I will also fix the MusicXML-to-Humdrum converter to translate arpeggiation lines.

These files contains arpeggiation lines:

```xml
T265_Ive-w40p47m102-105.xml
T318_Fal-w5p77h43m2-11.xml
T505_Mau-w110p6-7h4m4-8.xml
T570_Pro-w19p43h34m6-8.xml
```

(no RDS examples have arpeggiations).


I should also fix the rendering of the measure with the rest and three grace notes, which is like this in the original scan (like the Sibelius rendering):

<img width="433" alt="Screen Shot 2020-01-18 at 22 12 42" src="https://user-images.githubusercontent.com/3487289/72675881-bdce8380-3a3f-11ea-9b84-7507c8643041.png">


http://conquest.imslp.info/files/imglnks/usimg/7/78/IMSLP12646-Bartok_op14_Suite.pdf

**Comment by craigsapp** [comment]
Issue added to verovio-humdrum-viewer repository: https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/261

**Comment by aaronearlgraham** [comment]
T697, Copland, both harp parts missing arpeggio lines for entire excerpt

**Comment by craigsapp** [comment]
19 scores with arpeggiations that need conversion from MusicXML into Humdrum:

```
R534_Mai-w6p2m1-5.xml
T139A_Jan-w21p4m1-2.xml
T143_Jan-w39p9m18-23.xml
T158_Deb-w40p57h38m5-h39m2.xml
T160_Deb-w7p12hI1m1-4.xml
T206_Sch-w28p10-11m43i-46i.xml
T221_Sch-w34p160m10-11.xml
T233_Ive-w4p29s3-4.xml
T270_Ive-w45p21s1-2.xml
T302_Fal-w1p92m564-577.xml
T329_Bar-w17p11s3-4.xml
T398_Str-w56p35m166-169.xml
T446_Ber-w11p7m31-34.xml
T471_Mau-w42p45m284-289.xml
T495_Mau-w22p1m1-9.xml
T500_Mau-w63p5m30-33.xml
T518_Mau-w38p13m23-27.xml
T643_Hin-w39p61h39m1-4.xml
T697_Cop-w1v2p25m4-1h13m1.xml
```

**Comment by craigsapp** [comment]
Arpeggiation conversion implemented in MusicXML-to-Humdrum converter with commit https://github.com/craigsapp/humlib/commit/50a9f51553329aebacc552b02b7a09985290ebdd

All of the examples with arpeggiation have been reconverted, so they should be fixed in theory.

Here is the updated exemplar:


https://polyrhythm.humdrum.org/example/?id=329


<img width="1254" alt="Screen Shot 2020-01-19 at 20 43 04" src="https://user-images.githubusercontent.com/3487289/72699240-69d5a480-3afc-11ea-9607-e4acf7ef1e4c.png">

(measure 209 bass staff first beat now has arpeggiation converted automatically from MusicXML file).

Links to the examples that should have fixed arpeggiations:

https://polyrhythm.humdrum.org/example/?id=534
https://polyrhythm.humdrum.org/example/?id=139A
https://polyrhythm.humdrum.org/example/?id=143
https://polyrhythm.humdrum.org/example/?id=158
https://polyrhythm.humdrum.org/example/?id=160
https://polyrhythm.humdrum.org/example/?id=206
https://polyrhythm.humdrum.org/example/?id=221
https://polyrhythm.humdrum.org/example/?id=233
https://polyrhythm.humdrum.org/example/?id=270
https://polyrhythm.humdrum.org/example/?id=302
https://polyrhythm.humdrum.org/example/?id=329
https://polyrhythm.humdrum.org/example/?id=398
https://polyrhythm.humdrum.org/example/?id=446
https://polyrhythm.humdrum.org/example/?id=471
https://polyrhythm.humdrum.org/example/?id=495
https://polyrhythm.humdrum.org/example/?id=500
https://polyrhythm.humdrum.org/example/?id=518
https://polyrhythm.humdrum.org/example/?id=643
https://polyrhythm.humdrum.org/example/?id=697
