### ISSUE TITLE
Missing Crescendos

### ISSUE THREAD

**Issue by aaronearlgraham** [polyrhythm-project/polyrhythm-website#41]
T720, Copland, mm. 6, 2nd and 3rd cello parts, missing crescendos into mm. 7

Sib:
![image](https://user-images.githubusercontent.com/59717186/72690150-40058900-3ace-11ea-9cc8-43323b3655b8.png)

VHV:
![image](https://user-images.githubusercontent.com/59717186/72690154-45fb6a00-3ace-11ea-949e-39905204afc6.png)

**Comment by craigsapp** [comment]
This may be related to issue https://github.com/polyrhythm-project/polyrhythm-website/issues/16

**Comment by craigsapp** [comment]
Partially fixed in issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/266

Current rendering:

<img width="1035" alt="Screen Shot 2020-01-20 at 15 25 10" src="https://user-images.githubusercontent.com/3487289/72763550-1bc2ae80-3b99-11ea-80d5-aa310579db62.png">

Target rendering:

<img width="1192" alt="Screen Shot 2020-01-20 at 15 25 26" src="https://user-images.githubusercontent.com/3487289/72763552-1ebd9f00-3b99-11ea-9bc7-a410c7bf8eb9.png">

Just need to convert the _cresc._ into hairpins.

**Comment by craigsapp** [comment]
Now almost renders as expected:

<img width="1015" alt="Screen Shot 2020-01-20 at 20 58 45" src="https://user-images.githubusercontent.com/3487289/72776617-b639e680-3bc7-11ea-840d-49cc4622fd67.png">

Bottom slur needs lengthening.

**Comment by craigsapp** [comment]
Fix for bottom hairpin: https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/267

Now renders correctly:

<img width="1024" alt="Screen Shot 2020-01-20 at 22 13 56" src="https://user-images.githubusercontent.com/3487289/72779900-2a798780-3bd2-11ea-9e83-1a4072e46f2b.png">

**Comment by craigsapp** [comment]
Issue #16 also deals with dynamics, so I will close this issue.
