### ISSUE TITLE
Natural harmonics

### ISSUE THREAD

**Issue by aaronearlgraham** [polyrhythm-project/polyrhythm-website#43]
T725, Copland - mm. 3, 7, 8, 12 - viola, cello, and bass parts missing harmonic symbols above notes (circles)

Sib:
![image](https://user-images.githubusercontent.com/59717186/72690690-a640da80-3ad3-11ea-9613-e3d5aed825ee.png)

VHV:
![image](https://user-images.githubusercontent.com/59717186/72690695-bb1d6e00-3ad3-11ea-9a23-a0a9c4a8c156.png)

**Comment by craigsapp** [comment]
These scores have natural harmonics:

```
R392_Str-w33p52-54h74m1-h80m1.xml
R408_Web-w13p1-2m1-12.xml
R453_Ber-w15p362-363m118-121.xml
R534_Mai-w6p2m1-5.xml
T211_Sch-w30p22m130-134.xml
T226_Sch-w35p124m568-569.xml
T274_Rav-w26p27h18m1-6.xml
T285_Rav-w15p81h27m1-2.xml
T296_Rav-w31p1h1m1-8.xml
T331_Bar-w24p72m3-1h27m1-2.xml
T398_Str-w56p35m166-169.xml
T407_Web-w20p3am11-16.xml
T414A_Web-w24p4m19-20.xml
T414B_Web-w24p6m49-49.xml
T417_Web-w12p8m1-9.xml
T437_Ber-w9p22-23m16-20.xml
T725_Cop-w43p37-39m207-219.xml
T805_Bri-w21p23m405-411.xml
T808_Bri-w24p32m8-1h14m1-2.xml
T811_Bri-w29p12hIm6-14.xml
```

**Comment by craigsapp** [comment]
Should now be fixed in all examples with natural harmonics:

https://polyrhythm.humdrum.org/example/?id=392
https://polyrhythm.humdrum.org/example/?id=408
https://polyrhythm.humdrum.org/example/?id=453
https://polyrhythm.humdrum.org/example/?id=534
https://polyrhythm.humdrum.org/example/?id=211
https://polyrhythm.humdrum.org/example/?id=226
https://polyrhythm.humdrum.org/example/?id=274
https://polyrhythm.humdrum.org/example/?id=285
https://polyrhythm.humdrum.org/example/?id=296
https://polyrhythm.humdrum.org/example/?id=331
https://polyrhythm.humdrum.org/example/?id=398
https://polyrhythm.humdrum.org/example/?id=407
https://polyrhythm.humdrum.org/example/?id=414A
https://polyrhythm.humdrum.org/example/?id=414B
https://polyrhythm.humdrum.org/example/?id=417
https://polyrhythm.humdrum.org/example/?id=437
https://polyrhythm.humdrum.org/example/?id=725
https://polyrhythm.humdrum.org/example/?id=805
https://polyrhythm.humdrum.org/example/?id=808
https://polyrhythm.humdrum.org/example/?id=811

Exemplar:

<img width="315" alt="Screen Shot 2020-01-20 at 01 25 14" src="https://user-images.githubusercontent.com/3487289/72714681-f9427e00-3b23-11ea-9e40-7cff416dd04f.png">
