### ISSUE TITLE
Missing pizzicato text

### ISSUE THREAD

**Issue by rafaperlau** [polyrhythm-project/polyrhythm-website#68]
Ex. T794, Britten, Contrabass, bar 5: missing pizzicato mark on VHV.

VHV error:
![Sem título 1](https://user-images.githubusercontent.com/59910404/73094691-fc2bce80-3e95-11ea-955d-7b1da4027d88.jpg)

Sibelius PDF:
![Sem título 2](https://user-images.githubusercontent.com/59910404/73094711-06e66380-3e96-11ea-8ee6-c0e3b12a0009.jpg)

**Comment by craigsapp** [comment]
This is related to issue #40, but slightly different.  In this case the behavior of the Humdrum-to-MEI converter changed: before it was presumed that if there were no staff placement, the text would be displayed above the staff.  But I changed it to be required, and not to display the text if a staff placement is not present.  However, this situation is not good (as this example illustrates), so I will make text that needs to be displayed, but no staff placement is defined, be assigned to be displayed above the staff.

<img width="1307" alt="Screen Shot 2020-01-24 at 11 37 17" src="https://user-images.githubusercontent.com/3487289/73098487-5cbf0980-3e9e-11ea-96b5-21b7e593b453.png">

In the MusicXML-to-Humdrum conversion the above-staff information is lost (since this used to be the default).  I will also encode it explicitly in the MusicXML-to-Humdrum converter (this would solve the problem mentioned above, but doing both fixes is probably best).

**Comment by craigsapp** [comment]
The main thing that causes problems like this is that the text becomes detached from the notes by spine manipulators (such as `*^`).   This has been fixed with commit https://github.com/craigsapp/humlib/commit/82539a5fa01acd50e3b8b81c4170ab5949775c75

Also somewhat related, commit https://github.com/rism-ch/verovio/commit/74410bc67f227230c455204758dc3623426e1f37 will set the default position of text above the staff, and the previous commit should always given explicit positions of the text.

These two commits fix multiple examples which have missing text and/or the text is displayed on the wrong side of the staff.  Here is a sample (there are more TDS that are not listed):

https://polyrhythm.humdrum.org/example/?id=R130
https://polyrhythm.humdrum.org/example/?id=R180
https://polyrhythm.humdrum.org/example/?id=R222
https://polyrhythm.humdrum.org/example/?id=R279
https://polyrhythm.humdrum.org/example/?id=R295
https://polyrhythm.humdrum.org/example/?id=R332
https://polyrhythm.humdrum.org/example/?id=R392
https://polyrhythm.humdrum.org/example/?id=R428
https://polyrhythm.humdrum.org/example/?id=R443
https://polyrhythm.humdrum.org/example/?id=R453
https://polyrhythm.humdrum.org/example/?id=R456B
https://polyrhythm.humdrum.org/example/?id=R588
https://polyrhythm.humdrum.org/example/?id=R599
https://polyrhythm.humdrum.org/example/?id=R602
https://polyrhythm.humdrum.org/example/?id=R630
https://polyrhythm.humdrum.org/example/?id=R700
https://polyrhythm.humdrum.org/example/?id=R770
https://polyrhythm.humdrum.org/example/?id=R809
https://polyrhythm.humdrum.org/example/?id=T149
https://polyrhythm.humdrum.org/example/?id=T156

**Comment by craigsapp** [comment]
Updated example with fix:

https://polyrhythm.humdrum.org/example/?id=794

<img width="515" alt="Screen Shot 2020-01-25 at 07 52 05" src="https://user-images.githubusercontent.com/3487289/73123711-9bf56500-3f47-11ea-97c1-fccc62b343bf.png">

**Comment by craigsapp** [comment]
This issue should be sufficiently fixed now, so it can be closed. (Octave displacement of the bass part is a separate issue).
