### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#94]
ex. T586, Honegger, bass, lyrics look slightly different in VHV: missing hyphen after "mechant" and adding hyphen after "s'a". (Obs.: SIB .pdf has no proper hyphenation)

PDF

<img width="1027" alt="Screen Shot 2020-02-05 at 8 56 50 AM" src="https://user-images.githubusercontent.com/59900770/73864081-e7d0c580-47f5-11ea-98d2-04082a90c8bc.png">

VHV

<img width="813" alt="Screen Shot 2020-02-05 at 8 57 33 AM" src="https://user-images.githubusercontent.com/59900770/73864097-ed2e1000-47f5-11ea-8417-e581e1a13df5.png">

**Comment by craigsapp** [comment]
The underscore after "méchants" being dropped is OK in this case: the music is tightly spaced, so there is no need for an underscore.  Ideally the text should be split into two syllables one for the A and one for the B, and no underscore should be given.  The underscore should be used to indicate that multiple notes are sung to a single syllable, so it has no function here anyway.

For the added hyphen, `avancent` is presumably the word, so there is a missing hyphen in the Sibelius rendering.  In the MusicXML it seems to be added (otherwise it would not be magically added in the Humdrum score).  So in Sibelius there is some problem displaying the hyphen.

There will be nothing to fix for this example. However, it would be preferrable for the "méchants" word to be split into two separate syllables.  This is probably not necessary unless there is some use of the lyrics for computational analysis.
